
CREATE TABLE users (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    username VARCHAR NOT NULL,
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT DATE_TRUNC('seconds', CURRENT_TIMESTAMP) NOT NULL,
    updated_at TIMESTAMP DEFAULT DATE_TRUNC('seconds', CURRENT_TIMESTAMP) NOT NULL
);



CREATE TABLE books (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    name VARCHAR NOT NULL,
    pages VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT DATE_TRUNC('seconds', CURRENT_TIMESTAMP) NOT NULL,
    updated_at TIMESTAMP DEFAULT DATE_TRUNC('seconds', CURRENT_TIMESTAMP) NOT NULL,
    CONSTRAINT fk_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
);



